# Regenerates sw-manifest.js — the list of app-shell files the service
# worker precaches. Run this after adding/removing/renaming any shell file.
# Excludes variants/ (kept online-only), photos/ (runtime cache-first
# instead), and anything under .git or a PowerShell build script.
$root = $PSScriptRoot
$patterns = @(
  "index.html", "manifest.webmanifest", "style.css", "audio.js", "favicon.png",
  "css\*.css", "js\*.js", "data\*.js", "flags\*.svg", "icons\*.png", "vendor\*.js"
)
$files = @("./")
foreach ($p in $patterns) {
  Get-ChildItem -Path (Join-Path $root $p) -File -ErrorAction SilentlyContinue | ForEach-Object {
    $rel = $_.FullName.Substring($root.Length + 1) -replace '\\', '/'
    if ($rel -notlike "sw.js" -and $rel -notlike "sw-manifest.js") { $files += $rel }
  }
}
$files = $files | Sort-Object -Unique
$json = ($files | ForEach-Object { '  "' + $_ + '"' }) -join ",`n"
$out = "// Auto-generated by build-sw-list.ps1 - do not hand-edit. Re-run the`n// script after adding/removing an app-shell file.`nself.SW_MANIFEST = [`n$json`n];`n"
Set-Content -Path (Join-Path $root "sw-manifest.js") -Value $out -NoNewline -Encoding utf8
Write-Host "Wrote sw-manifest.js with $($files.Count) entries."
