// Torn Atlas service worker. Precaches the app shell (list generated by
// build-sw-list.ps1 into sw-manifest.js) so the game plays offline, and
// runtime-caches photos (cache-first) and Google Fonts (stale-while-revalidate).
// variants/ (Flag Voyage) is deliberately NOT precached — it still works
// online via a normal network fetch, same as before this worker existed.
importScripts("sw-manifest.js");

const CACHE_VERSION = "torn-atlas-v3";
const SHELL_CACHE = CACHE_VERSION + "-shell";
const RUNTIME_CACHE = CACHE_VERSION + "-runtime";
const CURRENT_CACHES = [SHELL_CACHE, RUNTIME_CACHE];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(SHELL_CACHE).then((cache) => cache.addAll(self.SW_MANIFEST)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => !CURRENT_CACHES.includes(k)).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

function isPhoto(url) { return url.pathname.startsWith("/photos/"); }
function isGoogleFont(url) { return url.hostname === "fonts.googleapis.com" || url.hostname === "fonts.gstatic.com"; }

// cache-first: check cache, fall back to network and store the response
async function cacheFirst(request, cacheName) {
  const cached = await caches.match(request);
  if (cached) return cached;
  const res = await fetch(request);
  if (res && res.ok) { const cache = await caches.open(cacheName); cache.put(request, res.clone()); }
  return res;
}
// stale-while-revalidate: serve cache immediately, refresh it in the background
async function staleWhileRevalidate(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  const network = fetch(request).then((res) => { if (res && res.ok) cache.put(request, res.clone()); return res; }).catch(() => cached);
  return cached || network;
}

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== location.origin && !isGoogleFont(url)) return; // let cross-origin (e.g. Wikipedia links) pass through untouched

  if (isPhoto(url)) { event.respondWith(cacheFirst(req, RUNTIME_CACHE)); return; }
  if (isGoogleFont(url)) { event.respondWith(staleWhileRevalidate(req, RUNTIME_CACHE)); return; }
  if (url.pathname.startsWith("/variants/")) return; // online-only, not precached

  // app shell: cache-first with a network fallback, so a fresh deploy still loads
  event.respondWith(
    caches.match(req).then((cached) => cached || fetch(req).catch(() => caches.match("./")))
  );
});
